name: Create Github Release

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: write

jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Github Release
      uses: softprops/action-gh-release@v1
      # with:
        # body: ""
        # body_path: CHANGELOG.txt
